[project]
name = "crt"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Flet developer", email = "you@example.com" }
]
dependencies = [
    "python-docx>=0.2.4",
    "flet>=0.80.5",
    "pysos>=1.3.0",
    "python-docx>=1.2.0",
    "pytorch>=1.0.2",
    "sentence-transformers>=5.2.3",
]

[dependency-groups]
dev = [
    "flet-cli>=0.80.5",
    "flet-desktop>=0.80.5",
    "flet-web>=0.80.5",
]

[tool.flet]
org = "com.mycompany"
product = "crt"
company = "Flet"
copyright = "Copyright (C) 2023-2026 by Flet"

[tool.flet.app]
path = "src"
